version: '3.4'

#####################################################
## DEFINE THE VARIABLES BASED ON YOUR SERVER SETUP ##
## THESE VARIABLES CAN BE EDITED LATER IF NEEDED   ##
#####################################################
## THIS STACK WILL DEPLOY THE DATABASE SERVER      ##
## PHPMYADMIN SERVER, MYAAC AND OTBR SERVER        ##
#####################################################

x-var1: &OTBR_VARS
- &f1 "HTTP_PORT=8080"                         # PORT USED BY YOUR AAC (80, 443, 8080 ARE THE MOST USED)
- &f2 "ENABLE_SSL=no"                          # ENABLE OR DISABLE SSL / BY DEFAULT IS DISABLED (yes/no)
- &f3 "SERVER_IP=127.0.0.1"                    # YOUR SERVER IP / CAN BE LOCAL IP OR PUBLIC IP
- &f4 "SERVER_NAME=canary"                     # YOUR SERVER NAME / CAN BE ANY
- &f5 "SERVER_LOCATION=South America"          # YOUR SERVER LOCATION / South America / Europe / Asia / North America / Africa
- &f6 "TZ=America/Sao_Paulo"                   # YOUR LOCAL TIME ZONE / FOR REFERENCE CHECK https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
- &f7 "WEBPAGE=https://my.webpage.com"         # URL TO YOUR AAC PAGE, REMEBER TO SET ACCORDINGLY WHEN IT IS HTTP OR HTTPS
- &f8 "DEFAULT_MAP=otbr"                       # IF YOU USE STANDARD OTBR GLOBAL MAP, SET IT TO (otbr), IF YOU USE CANARY OR CUSTOM MAP SET IT TO (none)

x-var2: &DB_VARS
- &f9 "MARIADB_USER=otbr"                      # USERNAME FOR YOUR DATABASE
- &f10 "MARIADB_PASSWORD=otbrpass"             # PASSWORD FOR YOUR DATABASE
- &f11 "MARIADB_ROOT_PASSWORD=@otbr@123#"      # PASSWORD FOR YOUR ROOT USER, PLEASE CHAGE IT FOR YOUR OWN SECURITY
- &f12 "MARIADB_DATABASE=canary"               # NAME FOR YOUR OTSERV DATABASE

x-var3: &DEFAULT_REPOS
- &f13 "AAC_REPO=https://github.com/sircurse/myaac.git"                      # LINK DO DOWNLOAD YOUR AAC SYSTEM / RECOMMENDED MYAAC https://github.com/sircurse/myaac.git
- &f14 "AAC_BRANCH=main"                                                     # AAC BRANCH TO DOWNLOAD / BY DEFAULT MAIN BY SIRCURSE / IF YOU CHOOSE A DIFFERENT REPOSITORY ENSURE YOU SELECT THE RIGHT BRANCH
- &f15 "DATAPACK_REPO=https://github.com/opentibiabr/otservbr-global.git"    # LINK DO DOWNLOAD YOUR DATAPACK REPOSITORY FILES / BY DEFAULT MAIN OTBR https://github.com/opentibiabr/otservbr-global.git
- &f16 "DATAPACK_BRANCH=main"                                                # DATAPACK BRANCH TO DOWNLOAD / IF YOU DON'T KNOW WHAT IT MEANS, LEAVE AS IS
- &f17 "DISTRO_REPO=https://github.com/opentibiabr/canary.git"               # LINK DO DOWNLOAD YOUR CANARY REPOSITORY FILES / BY DEFAULT MAIN CANARY https://github.com/opentibiabr/canary.git
- &f18 "DISTRO_BRANCH=main"                                                  # DISTRO BRANCH TO DOWNLOAD / IF YOU DON'T KNOW WHAT IT MEANS, LEAVE AS IS

#####################################################
#####################################################
#####################################################
##     DO NOT EDIT ANYTHING AFTER THIS POINT       ##
#####################################################
#####################################################
#####################################################

services:
  server:
    image: sircurse/otbr-server:latest
    hostname: otbr
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - "/srv/otbr/distro:/otbr/distro"
      - "/srv/otbr/server:/otbr/server"
      - "/srv/otbr/dbbkp:/otbr/dbbkp"
      - "/srv/otbr/certs:/otbr/certs"
      - "/srv/otbr/html:/var/www/html"
    ports:
      - 7171:7171
      - 7172:7172
#      - 8080:8080        # IF YOU ARE NOT USING A REVERSE PROXY, UNCOMMENT THIS LINE AND SET THE PORTS ACCORDINGLY
    entrypoint: /entrypoint.sh
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ENV_LOG_LEVEL=verbose
      - *f1
      - *f2
      - *f3
      - *f4
      - *f5
      - *f6
      - *f7
      - *f8
      - *f9
      - *f10
      - *f11
      - *f12
      - *f13
      - *f14
      - *f15
      - *f16
      - *f17
      - *f18
  db:
    image: mariadb:10.5
    hostname: otservdb
    restart: unless-stopped
    environment:
      - *f9
      - *f10
      - *f11
      - *f12
  phpmyadmin:
    image: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
networks:
  default:
    external:
      name: nginxproxymanager_default