version: '3.4'

#####################################################
## DEFINE THE VARIABLES BASED ON YOUR SERVER SETUP ##
## THESE VARIABLES CAN BE EDITED LATER IF NEEDED   ##
#####################################################
## THIS STACK WILL DEPLOY THE DATABASE SERVER      ##
## PHPMYADMIN SERVER, MYAAC AND OTBR SERVER        ##
#####################################################

x-var1: &OTBR_VARS
- &f1 "HTTP_PORT=8080"                         # PORT USED BY YOUR AAC (80, 443, 8080 ARE THE MOST USED)
- &f2 "ENABLE_SSL=no"                          # ENABLE OR DISABLE SSL / BY DEFAULT IS DISABLED (yes/no)
- &f3 "SERVER_IP=127.0.0.1"                    # SERVER IP / DEFAULT IS LOCAL (127.0.0.1)
- &f4 "SERVER_NAME=canary"                     # SERVER NAME / CAN BE ANY
- &f5 "SERVER_LOCATION=South America"          # SERVER LOCATION / South America / Europe / Asia / North America / Africa
- &f6 "TZ=America/Sao_Paulo"                   # LOCAL TIME ZONE / CHECK https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
- &f7 "WEBPAGE=https://my.webpage.com"         # AAC WEB ADDRESS, REMEBER TO SET ACCORDINGLY WHEN IT IS HTTP OR HTTPS
- &f8 "DEFAULT_MAP=otbr"                       # DEFAULT OTBR GLOBAL MAP (otbr), IF YOU USE CANARY OR CUSTOM MAP SET TO (none)

x-var2: &DB_VARS
- &f9 "MARIADB_USER=otbr"                      # USERNAME FOR DATABASE
- &f10 "MARIADB_PASSWORD=otbrpass"             # PASSWORD FOR DATABASE
- &f11 "MARIADB_ROOT_PASSWORD=@otbr@123#"      # PASSWORD FOR DB ROOT USER, PLEASE CHAGE IT FOR YOUR OWN SECURITY
- &f12 "MARIADB_DATABASE=canary"               # NAME FOR YOUR OTSERV DATABASE

x-var3: &DEFAULT_REPOS
- &f13 "AAC_REPO=https://github.com/sircurse/myaac.git"                      # LINK OF AAC SYSTEM'S REPO / RECOMMENDED MYAAC https://github.com/sircurse/myaac.git
- &f14 "AAC_BRANCH=main"                                                     # AAC BRANCH TO DOWNLOAD / BY DEFAULT MAIN
- &f15 "DATAPACK_REPO=https://github.com/opentibiabr/otservbr-global.git"    # LINK OF DATAPACK'S REPO / BY DEFAULT OTBR https://github.com/opentibiabr/otservbr-global.git
- &f16 "DATAPACK_BRANCH=main"                                                # DATAPACK BRANCH TO DOWNLOAD / BY DEFAULT MAIN
- &f17 "DISTRO_REPO=https://github.com/opentibiabr/canary.git"               # LINK OF DISTRO'S REPO / BY DEFAULT OTBR CANARY https://github.com/opentibiabr/canary.git
- &f18 "DISTRO_BRANCH=main"                                                  # DISTRO BRANCH TO DOWNLOAD / BY DEFAULT MAIN

x-var4: &SYTEM_SETTINGS
- &s1 "CHECK_DISTRO_UPDATES=yes"                # CHECK IF YOUR DISTRO'S HAS NEW COMMITS/UPDATES (yes / no)
- &s2 "CHECK_DATAPACK_UPDATES=yes"              # CHECK IF YOUR DATAPACK'S HAS NEW COMMITS/UPDATES (yes / no)
- &s3 "CHECK_AAC_UPDATES=yes"                   # CHECK IF YOUR AAC'S HAS NEW COMMITS/UPDATES (yes / no)
- &s4 "CHECK_VA_UPDATES=yes"                    # CHECK IF YOUR OTBR VIRTUAL APPLIANCE'S HAS NEW COMMITS/UPDATES (yes / no)
- &s5 "AUTOUPDATE_VA=yes"                       # AUTO-UPDATE YOUR OTBR VIRTUAL APPLIANCE (yes / no)

#####################################################
#####################################################
#####################################################
##     DO NOT EDIT ANYTHING AFTER THIS POINT       ##
#####################################################
#####################################################
#####################################################

services:
  server:
    image: sircurse/otbr-va:latest
    hostname: otbr
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - "/srv/otbr/distro:/otbr/distro"
      - "/srv/otbr/server:/otbr/server"
      - "/srv/otbr/dbbkp:/otbr/dbbkp"
      - "/srv/otbr/certs:/otbr/certs"
      - "/srv/otbr/html:/var/www/html"
    ports:
      - 7171:7171
      - 7172:7172
#      - 8080:8080        # IF YOU ARE NOT USING A REVERSE PROXY, UNCOMMENT THIS LINE AND SET THE PORTS ACCORDINGLY
    entrypoint: /entrypoint.sh
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ENV_LOG_LEVEL=verbose
      - *f1
      - *f2
      - *f3
      - *f4
      - *f5
      - *f6
      - *f7
      - *f8
      - *f9
      - *f10
      - *f11
      - *f12
      - *f13
      - *f14
      - *f15
      - *f16
      - *f17
      - *f18
      - *s1
      - *s2
      - *s3
      - *s4
      - *s5
  db:
    image: mariadb:10.5
    hostname: otservdb
    restart: unless-stopped
    environment:
      - *f9
      - *f10
      - *f11
      - *f12
  phpmyadmin:
    image: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
networks:
  default:
    external:
      name: nginxproxymanager_default