version: '3.4'
networks:
  nginxproxymanager_default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/16
      driver: default
    name: nginxproxymanager_default
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      nginxproxymanager_default:
        ipv4_address: 172.18.0.150
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "dbuser"
      DB_MYSQL_PASSWORD: "dbpass"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'yobasystems/alpine-mariadb:latest'
    restart: unless-stopped
    networks:
      nginxproxymanager_default:
        ipv4_address: 172.18.0.151
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
    volumes:
      - ./data/mysql:/var/lib/mysql
